
---
title: "Assignment 2"
author: "pb649@scarletmail.rutgers.edu"
date: "2/13/2023"
output: html_document
---

```{r}
library(ggplot2)
library(lattice)
library(ggridges)
library(ggvis)
library(ggthemes)
library(cowplot)
library(gapminder)
library(gganimate)
library(dplyr)
library(tidyverse)
library(grid)
library(gridExtra)
library(RColorBrewer)
library(readr)
sparrows <- read_csv("~/Downloads/Bumpus_sparrows.csv")
sparrows
```

sparrows

# Scatter plot
```{r}

ggplot(sparrows, aes(x=L_humerous,y=Alar_extent))+geom_point(aes(color=Total_length)) 

ggplot(sparrows, aes(x=L_beak_head,y=L_keel_sternum))+geom_point(aes(color=Total_length)) 

ggplot(sparrows, aes(x=L_beak_head,y=Total_length)) + xlim(30,32) + geom_point(colour="red",pch=12)

ggplot(sparrows, aes(x=L_beak_head,y=L_humerous)) + facet_wrap(~Total_length) + geom_point(aes(color=Survivorship))


```

# Histogram

```{r}
ggplot(sparrows, aes(Total_length))+geom_histogram(fill='coral', color='white',bins=10)
ggplot(sparrows, aes(L_beak_head))+geom_histogram(aes(fill=after_stat(count)))
```
  
# Bar chart
```{r}
ggplot(sparrows, aes(x=L_humerous, fill=Total_length)) + geom_bar()+theme_bw()
ggplot(sparrows, aes(Survivorship))+ geom_bar(position="stack", fill='seagreen') 
ggplot(sparrows, aes(Total_length)) + facet_grid(.~Survivorship) + geom_bar(position="dodge",fill='violet')
```

# Regression
```{r}
ggplot(sparrows, aes(x=Alar_extent,y=L_beak_head))+geom_point()+ geom_smooth(method=lm,se= FALSE)
ggplot(sparrows, aes(x=Total_length,y=Alar_extent)) + geom_point() + stat_smooth()
```

# Violin plot
```{r}
ggplot(sparrows, aes(x=Survivorship,y=Total_length)) + geom_violin()
ggplot(sparrows, aes(x=Survivorship,y=L_keel_sternum)) + geom_violin()
ggplot(sparrows, aes(x=Survivorship,y=L_humerous)) + geom_violin()
ggplot(sparrows, aes(x=Survivorship,y=L_beak_head)) + geom_violin()
ggplot(sparrows, aes(x=Survivorship,y=Alar_extent)) + geom_violin()
```

# box plot
```{r}
ggplot(sparrows, aes(x=Survivorship,y=Alar_extent)) + geom_boxplot()
ggplot(sparrows, aes(x=Total_length,y=L_beak_head)) + geom_boxplot() + coord_flip()
```


# density plot and ggridges
```{r}
ggplot(sparrows, aes(x=Total_length)) + geom_density() 
ggplot(sparrows, aes(x=L_humerous, fill=Survivorship)) + geom_density() 

ggplot(sparrows, aes(x=L_keel_sternum, fill=Survivorship)) + geom_density() 

ggplot(sparrows, aes(x=Alar_extent, fill=Survivorship)) + geom_density(alpha=0.3, aes(y=after_stat(scaled))) 

ggplot(sparrows, aes(x=Total_length, y=Survivorship)) + geom_density_ridges() 

ggplot(sparrows, aes(x=L_beak_head)) + geom_density(color='pink') 

ggplot(sparrows, aes(x=L_humerous, y=Survivorship)) + geom_density_ridges() 
```


# hexbin
```{r}
ggplot(sparrows, aes(x=Total_length, y=Alar_extent)) + geom_hex()
```

# with ggthemes (see also ggsci, ggthemr)
```{r}
lastplot <- ggplot(sparrows, aes(x=Total_length, y=Alar_extent)) + xlim(150,170) + geom_point(aes(color=Survivorship)) + stat_smooth() + 
  labs(x="Total Length", y="Alar Extent", title="Sparrow Data") 
lastplot + theme_bw()
lastplot + theme_cowplot()
lastplot + theme_dark()
lastplot + theme_economist()
lastplot + theme_fivethirtyeight()
lastplot + theme_tufte()
lastplot + theme_wsj()
```

## Inference 

* We can see that in most of the plots that the outliers didn't survive and the survivors are converging towards the centre.







